### ISSUE TITLE
Failure to Auth

### ISSUE THREAD

**Issue by uplusion23** [SciencyScience/BattlelogMobile#1]
Axios responds with the following error when authenticating.
```
data: {
      jsonrpc: '2.0',
      id: 'f4f57281-c94a-47cd-8c9a-6cb9ee3fa28d',
      error: { message: "Invalid param: 'code' malformed", code: -32602 }
    }
```

**Comment by rydklein** [comment]
I believe that is caused by a failure to login. I can look into this in more detail tomorrow, but I just tested this out, and everything works fine given I provide accurate login information. One easy thing to try: ensure that your account does not have two factor authentication enabled (email or otherwise). This codebase was never more than a proof of concept, so I never added any creature comforts. I'm in the process of writing up a simple Readme that explains all of this and more. I was not expecting for anyone to ever see this code but me.

**Comment by rydklein** [comment]
When the getEALoginCode flow fails, instead of providing an error, it just passes on a bunch of garbled junk to getCompanionSession, which promptly returns a 400 (Bad Request). If you've ensured that your login was correct and doesn't require two-factor, and you're still getting this issue, I suggest pulling up your debugger of choice and figuring out exactly what is going on. If you can't figure it out, I'm glad to help.

**Comment by rydklein** [comment]
I just want to stress that none of the code here should be used. If I had to redo this, I'd use something like [node-fetch-cookies](https://www.npmjs.com/package/node-fetch-cookies) -- my cookie implementation was my first foray into programming in a long, long time and not something I'm particularly proud of, and the overall structure of this application is disgusting.

**Comment by uplusion23** [comment]
No worries! It's definitely because of the 2FA. I've went ahead and performed my own method (my program uses electron, so I'm able to have the user sign in via navigating to the page directly, therefore solving the 2FA), which I'll be sure to share the details, but for auth we only need three or four of the cookies. The cookies starting with `__` don't seem to be required for requests but I'm unsure what they are used for.
